spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
#        - id: test_route
#          uri: https://www.baidu.com
#          predicates:
#            - Query=url,baidu
#        - id: qq_route
#          uri: https://www.qq.com
#          predicates:
#            - Query=url,qq

        - id: product_route
          uri: lb://product
          predicates:
              - Path=/api/product/**
          filters:
              - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast #lb负载均衡
          predicates:
            - Path=/api/** #只要带有api的请求都路由到renrenfast
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment} #前面的路径重写为后面的




server:
  port: 88
